import * as React from "react";
import { useState } from "react";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import Head from "next/head";

const Onboard = () => {
  const [data, setData] = React.useState([]);
  const getInfo = async () => {
    try {
      const getData = await axios.get("http://localhost:5000/onboard");
      console.log("getData: ", getData?.data?.data);
      setData(getData?.data?.data);
    } catch (err) {
      console.log(err);
    }
  };

  React.useEffect(() => {
    getInfo();
  }, []);
  return (
    <>
      <Head>
        <title>Travelopia | Submission</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className="text-lg font-bold">Travelopia form submission&nbsp;</p>
        <div className="grid grid-cols-1 gap-2">
          {data &&
            data?.map((item: any, index: number) => {
              return (
                <ul
                  key={index}
                  className="border-[1px] rounded-lg border-black/50 px-4 py-2"
                >
                  <li>
                    Name: <span className="font-semibold">{item?.name}</span>
                  </li>
                  <li>
                    Email: <span className="font-semibold">{item?.email}</span>
                  </li>
                  <li>
                    Destination:{" "}
                    <span className="font-semibold">{item?.destination}</span>
                  </li>
                  <li>
                    Passengers:{" "}
                    <span className="font-semibold">{item?.passengers}</span>
                  </li>
                  <li>
                    Budget per person:{" "}
                    <span className="font-semibold">
                      {item?.budget_per_person}
                    </span>
                  </li>
                </ul>
              );
            })}
        </div>
      </main>
    </>
  );
};

export default Onboard;
